repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    # Ruff version.
    rev: "v0.0.264"
    hooks:
      - id: ruff
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: local
    hooks:
      - id: test
        name: test
        entry: poetry run pytest
        language: system
        types: [python]
        pass_filenames: false
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v2.40.0
    hooks:
      - id: commitizen
      - id: commitizen-branch
        stages: [push]
  # TODO: Update this later but adding docstrings to every test will be so painful
  # - repo: https://github.com/econchick/interrogate
  #   rev: 1.5.0
  #   hooks:
  #     - id: interrogate
  #       args: [--fail-under=80, --verbose]
